version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: pokemon-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - pokemon-db-data:/var/lib/mysql
      - ./docker/mysql-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 5
      timeout: 5s

  redis:
    image: redis:7-alpine
    container_name: pokemon-redis
    restart: always
    command: ["redis-server", "--requirepass", "${REDIS_PASS}"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      REDIS_ADDR: redis:6379
      REDIS_PASS: ${REDIS_PASS}
    ports:
      - "8080:8080" 

volumes:
  pokemon-db-data:
  redis-data:
